AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CvGenerator:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_handler.lambda_handler
      Role: arn:aws:iam::277469568219:role/full-access-role
      Code:
        S3Bucket: cv-generator-2
        S3Key: lambda_package.zip
      Runtime: python3.8

  MyApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyAPI

  MyApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyApiGateway.RootResourceId
      PathPart: myresource
      RestApiId: !Ref MyApiGateway

  MyApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref MyApiResource
      RestApiId: !Ref MyApiGateway
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CvGenerator.Arn}/invocations"
      MethodResponses:
        - StatusCode: 200
